"""Pure, testable contracts for Saitenka's future session runtime."""

from saitenka.runtime.deadlines import DeadlinePair, DeadlineRegistry
from saitenka.runtime.diagnostics import DiagnosticKind, DiagnosticRecord
from saitenka.runtime.effects import (
    AsyncEffect,
    CancelEffect,
    CoreControl,
    Effect,
    EffectDeadline,
    EffectError,
    EffectId,
    EffectOutcome,
    EmitDiagnostic,
    ExpireEffect,
    Owner,
    ScheduleTimer,
    SendMpvCommand,
    StopSession,
    SubmitJob,
)
from saitenka.runtime.events import (
    CloseRequested,
    CommandHandled,
    CommandOutcome,
    CommandReason,
    ConnectionLost,
    ConnectionReady,
    ConnectionReplaced,
    EffectFinished,
    EffectOutcomeEvent,
    EventEnvelope,
    EventOrigin,
    RawMpvEvent,
    RuntimeEvent,
    UserCommand,
)
from saitenka.runtime.jobs import JobBroker, JobLanePolicy
from saitenka.runtime.limits import DEFAULT_RUNTIME_LIMITS, RuntimeLimits
from saitenka.runtime.mailbox import MailboxFull, SessionMailbox, TrafficClass
from saitenka.runtime.reactor import SessionReactor
from saitenka.runtime.state import (
    ReduceResult,
    RoutedEvent,
    RouteError,
    RouteKey,
    SessionReducer,
    SessionState,
    TurnResult,
)
from saitenka.runtime.surfaces import (
    SurfaceAction,
    SurfaceRuntime,
    SurfaceSnapshot,
    SurfaceStatus,
    SurfaceTransaction,
    SurfaceTransactionOutcome,
)
from saitenka.runtime.timers import TimerScheduler

__all__ = [
    "DEFAULT_RUNTIME_LIMITS",
    "AsyncEffect",
    "CancelEffect",
    "CloseRequested",
    "CommandHandled",
    "CommandOutcome",
    "CommandReason",
    "ConnectionLost",
    "ConnectionReady",
    "ConnectionReplaced",
    "CoreControl",
    "DeadlinePair",
    "DeadlineRegistry",
    "DiagnosticKind",
    "DiagnosticRecord",
    "Effect",
    "EffectDeadline",
    "EffectError",
    "EffectFinished",
    "EffectId",
    "EffectOutcome",
    "EffectOutcomeEvent",
    "EmitDiagnostic",
    "EventEnvelope",
    "EventOrigin",
    "ExpireEffect",
    "JobBroker",
    "JobLanePolicy",
    "MailboxFull",
    "Owner",
    "RawMpvEvent",
    "ReduceResult",
    "RouteError",
    "RouteKey",
    "RoutedEvent",
    "RuntimeEvent",
    "RuntimeLimits",
    "ScheduleTimer",
    "SendMpvCommand",
    "SessionMailbox",
    "SessionReactor",
    "SessionReducer",
    "SessionState",
    "StopSession",
    "SubmitJob",
    "SurfaceAction",
    "SurfaceRuntime",
    "SurfaceSnapshot",
    "SurfaceStatus",
    "SurfaceTransaction",
    "SurfaceTransactionOutcome",
    "TimerScheduler",
    "TrafficClass",
    "TurnResult",
    "UserCommand",
]
