"""Emit the [mine.card_format] marker table (Markdown) from :data:`card_markers.CATALOG` to stdout.

Committed output lives at ``docs/usage/_card_format_markers.md`` and is ``include-markdown``'d into the
Configuration page, so the docs table can't drift from the code (a golden test asserts they match).
Regenerate after touching the catalog: ``uv run poe docs-markers``.
"""

from __future__ import annotations

import sys

from saitenka.app.card_markers import CATALOG, Marker

_HEADER = "<!-- Generated by `uv run poe docs-markers` from card_markers.CATALOG — do not edit by hand. -->"


def _table(markers: list[Marker], value_header: str) -> str:
    rows = [f"| `{{{m.name}}}` | {m.source} |" for m in markers]
    return "\n".join([f"| Marker | {value_header} |", "| --- | --- |", *rows])


def render() -> str:
    """The full Markdown fragment: a table of shippable markers, then the not-yet-supported ones."""
    ship = [m for m in CATALOG if m.status == "ship"]
    deferred = [m for m in CATALOG if m.status == "deferred"]
    blocks = [
        _HEADER,
        "",
        _table(ship, "Fills with"),
        "",
        "**Not yet supported** — named so a blank field isn't a surprise:",
        "",
        _table(deferred, "Would fill with"),
    ]
    return "\n".join(blocks) + "\n"


def main() -> None:
    sys.stdout.write(render())


if __name__ == "__main__":
    main()
