"""Public types for the compiled libasslite extension."""

from collections.abc import Sequence
from os import PathLike

type StrPath = str | PathLike[str]

class AssImageLayer:
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def stride(self) -> int: ...
    @property
    def bitmap(self) -> bytes: ...
    @property
    def color(self) -> int: ...
    @property
    def dst_x(self) -> int: ...
    @property
    def dst_y(self) -> int: ...
    @property
    def image_type(self) -> int: ...

class AssRenderResult:
    @property
    def layers(self) -> list[AssImageLayer]: ...
    @property
    def detect_change(self) -> int: ...

class AssRenderer:
    def __init__(
        self,
        ass: bytes,
        fonts: Sequence[tuple[str, bytes]] = (),
        *,
        library_path: StrPath | None = None,
    ) -> None: ...
    def render(
        self,
        timestamp_ms: int,
        frame_size: tuple[int, int],
        storage_size: tuple[int, int],
        *,
        pixel_aspect: float | None = None,
    ) -> AssRenderResult: ...
    def close(self) -> None: ...
    def library_version(self) -> int: ...
    def library_path(self) -> str: ...

def library_version(*, library_path: StrPath | None = None) -> int: ...
