"""Emit the CLI reference page (Markdown) from the cyclopts app to stdout.

Committed output lives at ``docs/usage/cli.md`` so Read the Docs renders static Markdown with no package
import at build time (overlay has a rust component — installing it into the docs env would be fragile).
Regenerate after changing commands: ``uv run poe docs-cli``. ``show=False`` commands stay out
(``include_hidden=False``).
"""

from __future__ import annotations

import sys

from overlay.app.cli import app

_HEADER = """\
<!-- Generated by `uv run poe docs-cli` from the cyclopts app — do not edit by hand. -->
"""


def main() -> None:
    body = app.generate_docs(output_format="markdown", include_hidden=False, heading_level=1)
    sys.stdout.write(_HEADER + "\n" + body)


if __name__ == "__main__":
    main()
