"""Generate ``src/saitenka/render/_uax14_classes.py`` — the compact Line_Break class table — from the
vendored (gzipped) ``tests/fixtures/uax14/LineBreak.txt.gz`` UCD property file.

Emits a gap-free, coalesced ``(start, class_id)`` table covering U+0000..U+10FFFF so a runtime lookup
is one bisect, no import-time text parse. Re-run after bumping the vendored ``LineBreak.txt.gz``:

    uv run python tools/gen_uax14.py
"""

from __future__ import annotations

import gzip
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "tests" / "fixtures" / "uax14" / "LineBreak.txt.gz"
OUT = ROOT / "src" / "saitenka" / "render" / "_uax14_classes.py"

MAX_CP = 0x10FFFF

# The raw Line_Break property (what LineBreakTest.txt is generated against) is @missing XX for every
# unlisted code point; LB1 then resolves XX→AL. The derived-property ID/PR defaults for unassigned
# CJK/currency blocks are deliberately NOT applied — assigned characters are listed explicitly, and the
# unassigned ones never reach the renderer.


def _build() -> tuple[list[int], list[str]]:
    text = gzip.decompress(SRC.read_bytes()).decode("utf-8")
    cls = ["XX"] * (MAX_CP + 1)
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        rng, name = (f.strip() for f in line.split(";"))
        if ".." in rng:
            lo, hi = (int(x, 16) for x in rng.split(".."))
        else:
            lo = hi = int(rng, 16)
        for cp in range(lo, hi + 1):
            cls[cp] = name
    starts: list[int] = [0]
    classes: list[str] = [cls[0]]
    for cp in range(1, MAX_CP + 1):
        if cls[cp] != classes[-1]:
            starts.append(cp)
            classes.append(cls[cp])
    return starts, classes


def main() -> None:
    starts, classes = _build()
    names = sorted(set(classes))
    ids = {n: i for i, n in enumerate(names)}
    body = [
        '"""Generated by ``tools/gen_uax14.py`` from the vendored UAX #14 LineBreak.txt — do not edit."""',
        "",
        "from __future__ import annotations",
        "",
        f"CLASS_NAMES: tuple[str, ...] = {tuple(names)!r}",
        "",
        "# Parallel arrays: RANGE_STARTS[i] is the first code point of a run whose Line_Break class id is",
        "# RANGE_CLASSES[i] (index into CLASS_NAMES). Gap-free over U+0000..U+10FFFF; bisect to look up.",
        f"RANGE_STARTS: tuple[int, ...] = {tuple(starts)!r}",
        f"RANGE_CLASSES: tuple[int, ...] = {tuple(ids[c] for c in classes)!r}",
        "",
    ]
    OUT.write_text("\n".join(body), encoding="utf-8")
    print(f"wrote {OUT} — {len(starts)} runs, {len(names)} classes")


if __name__ == "__main__":
    main()
