"""Pure subtitle parsing and cue navigation."""

from saitenka.subtitles import converted
from saitenka.subtitles.ass import (
    AssColorRewrite,
    AssStyle,
    AssStyleCatalog,
    TokenColor,
    UnsupportedAssEvent,
    allocate_token_colors,
    decode_ass_event,
    parse_ass_event_line,
    parse_ass_styles,
    rewrite_ass_event,
    serialize_ass_event_line,
    shift_ass_dialogue,
    source_primary_bgr_colors,
)
from saitenka.subtitles.ass_geometry import (
    MAX_ASS_SOURCE_BYTES,
    PreparedAssFrame,
    PreparedAssGeometry,
    authored_ass_rows_at,
    canonical_active_ass_rows,
    prepare_ass_hit_map,
    prepare_ass_hit_map_frame,
)
from saitenka.subtitles.document import (
    AnnotatedSubtitleEvent,
    DecodedSubtitleEvent,
    DrawingSpan,
    RawSubtitleEvent,
    RawSubtitleTrack,
    RawTextSpan,
    SubtitleAttachment,
    SubtitleEventId,
    SubtitleFrameId,
    SubtitleTrackId,
    TokenAnnotation,
)
from saitenka.subtitles.geometry import (
    FontProvider,
    FontSetup,
    GeometryBackend,
    GeometryPaletteEntry,
    GeometryRequest,
    GeometrySnapshot,
    GeometryVariant,
    Rect,
    RendererState,
    TokenGeometry,
)
from saitenka.subtitles.index import CueIndex
from saitenka.subtitles.model import Cue
from saitenka.subtitles.null_backend import NullGeometryBackend
from saitenka.subtitles.parsers import parse_ass, parse_cues, parse_srt

__all__ = [
    "MAX_ASS_SOURCE_BYTES",
    "AnnotatedSubtitleEvent",
    "AssColorRewrite",
    "AssStyle",
    "AssStyleCatalog",
    "Cue",
    "CueIndex",
    "DecodedSubtitleEvent",
    "DrawingSpan",
    "FontProvider",
    "FontSetup",
    "GeometryBackend",
    "GeometryPaletteEntry",
    "GeometryRequest",
    "GeometrySnapshot",
    "GeometryVariant",
    "NullGeometryBackend",
    "PreparedAssFrame",
    "PreparedAssGeometry",
    "RawSubtitleEvent",
    "RawSubtitleTrack",
    "RawTextSpan",
    "Rect",
    "RendererState",
    "SubtitleAttachment",
    "SubtitleEventId",
    "SubtitleFrameId",
    "SubtitleTrackId",
    "TokenAnnotation",
    "TokenColor",
    "TokenGeometry",
    "UnsupportedAssEvent",
    "allocate_token_colors",
    "authored_ass_rows_at",
    "canonical_active_ass_rows",
    "converted",
    "decode_ass_event",
    "parse_ass",
    "parse_ass_event_line",
    "parse_ass_styles",
    "parse_cues",
    "parse_srt",
    "prepare_ass_hit_map",
    "prepare_ass_hit_map_frame",
    "rewrite_ass_event",
    "serialize_ass_event_line",
    "shift_ass_dialogue",
    "source_primary_bgr_colors",
]
