"""Pure UAX #14 line-breaking (Unicode Line Breaking Algorithm) + JIS X 4051 kinsoku.

No third-party dep gives this for free under our licence constraints, so it is a self-contained pass
over the vendored Line_Break property table (``_uax14_classes`` — generated by ``tools/gen_uax14.py``)
plus ``unicodedata`` for the few rules that need General_Category / East_Asian_Width. It is the single
source of break opportunities the flow renderer wraps on, replacing the ad-hoc ``NO_START``/``NO_END``
greedy kinsoku that used to live in ``render.flow``/``render.layout``.

Two surfaces:

- :func:`break_opportunities` — character-level UAX #14, validated byte-for-byte against the vendored
  ``LineBreakTest.txt`` conformance corpus (``tests/test_linebreak.py``). ``result[i]`` is the break
  status *before* char ``i`` (``MANDATORY`` / ``ALLOWED`` / ``PROHIBITED``); ``result[0]`` is always
  ``PROHIBITED`` (sot ×).
- :func:`wrap_units` — greedy width-fill over atomic *units* (a ruby base+reading group is one unit, so
  a break never lands inside it), using the same character algorithm at unit boundaries.
"""

from __future__ import annotations

import unicodedata
from bisect import bisect_right
from functools import cache, lru_cache
from typing import TYPE_CHECKING

from overlay.render._uax14_classes import CLASS_NAMES, RANGE_CLASSES, RANGE_STARTS

if TYPE_CHECKING:
    from collections.abc import Callable, Sequence

MANDATORY = "mandatory"
ALLOWED = "allowed"
PROHIBITED = "prohibited"

# Extended_Pictographic base ranges needed by LB30b (emoji). The renderer only ever sees BMP emoji via
# fonts, and the corpus exercises a handful; a tiny explicit table avoids vendoring emoji-data.txt.
_EXT_PICT = (
    (0x203C, 0x203C),
    (0x2049, 0x2049),
    (0x2122, 0x2122),
    (0x2139, 0x2139),
    (0x2194, 0x21AA),
    (0x231A, 0x231B),
    (0x2328, 0x2328),
    (0x23CF, 0x23F3),
    (0x23F8, 0x23FA),
    (0x24C2, 0x24C2),
    (0x25AA, 0x25FE),
    (0x2600, 0x27BF),
    (0x2934, 0x2935),
    (0x2B05, 0x2BFF),
    (0x3030, 0x3030),
    (0x303D, 0x303D),
    (0x3297, 0x3299),
    (0x1F000, 0x1FAFF),
    (0x1FC00, 0x1FFFD),
)


def _lb_class(cp: int) -> str:
    """Raw Line_Break class of a code point (before LB1 resolution)."""
    return CLASS_NAMES[RANGE_CLASSES[bisect_right(RANGE_STARTS, cp) - 1]]


def _is_ext_pict(cp: int) -> bool:
    return any(lo <= cp <= hi for lo, hi in _EXT_PICT)


# Per-code-point lookups are memoised: real text reuses a small kanji/kana/latin working set, so caching
# the class resolution + the unicodedata (category / East_Asian_Width) probes keeps wrapping a heavy
# entry off the per-boundary unicodedata cost. Pure functions of one code point; the caches are bounded
# in practice by the script's character inventory.
@cache
def _resolve(cp: int) -> str:
    """LB1: map the ambiguous classes to a concrete one. AI/SG/XX→AL; SA→CM for combining marks else
    AL; CJ→NS (strict, the JIS default the tooltip wants); the rest pass through."""
    c = _lb_class(cp)
    if c in {"AI", "SG", "XX"}:
        return "AL"
    if c == "SA":
        return "CM" if unicodedata.category(chr(cp)) in {"Mn", "Mc"} else "AL"
    if c == "CJ":
        return "NS"
    return c


def break_opportunities(text: str) -> list[str]:
    """UAX #14 break status *before* each character of ``text`` (``result[i]`` governs the boundary
    between ``text[i-1]`` and ``text[i]``). ``result[0]`` is ``PROHIBITED`` (sot). Empty text → ``[]``."""
    if not text:
        return []
    out = [PROHIBITED] * len(text)  # LB2/LB9: sot and combining-mark boundaries are always ×
    bcls, bcps, bidx = _bases(
        text
    )  # LB9/LB10: fold CM/ZWJ onto their base, run rules over the bases
    for k in range(1, len(bcls)):
        out[bidx[k]] = _boundary(bcps, bcls, k)
    return out


def _bases(text: str) -> tuple[list[str], list[int], list[int]]:
    """Reduce ``text`` to its LB9 base sequence: a CM/ZWJ folds onto the preceding base (unless that base
    is a mandatory break or space), so it starts no new base and keeps a ``×`` before it. A standalone
    CM/ZWJ (after sot/break/space) becomes AL (LB10), except a standalone ZWJ stays ZWJ for LB8a."""
    bcls: list[str] = []
    bcps: list[int] = []
    bidx: list[int] = []
    for i, ch in enumerate(text):
        cp = ord(ch)
        c = _resolve(cp)
        if c in {"CM", "ZWJ"} and bcls and bcls[-1] not in {"BK", "CR", "LF", "NL", "SP", "ZW"}:
            continue  # attaches to its base — not a break boundary, not a new base
        bcls.append("AL" if c == "CM" else c)
        bcps.append(cp)
        bidx.append(i)
    return bcls, bcps, bidx


def _boundary(cps: Sequence[int], cls: Sequence[str], i: int) -> str:
    """Break status before base ``i`` (LB4–LB18) — first matching rule wins; LB19+ is in
    :func:`_lb19_onward`. ``cps``/``cls`` are the LB9 base sequence, so no combining marks remain."""
    b, a = cls[i - 1], cls[i]

    # LB4/LB5 mandatory breaks; LB6 never break before one.
    if b == "BK" or (b == "CR" and a != "LF") or b in {"LF", "NL"}:
        return MANDATORY
    if a in {"BK", "CR", "LF", "NL"}:
        return PROHIBITED
    # LB7 no break before SP/ZW. LB8 break after ZW (across SP). LB8a no break after ZWJ.
    if a in {"SP", "ZW"}:
        return PROHIBITED
    if _prev_nonsp(cls, i) == "ZW":
        return ALLOWED
    if b == "ZWJ":
        return PROHIBITED
    r = _lb11_18(cps, cls, i, b, a)
    if r is not None:
        return r
    r = _lb19_onward(cps, cls, i, b, a)
    return r if r is not None else ALLOWED  # LB31: break everywhere else


def _lb11_18(cps: Sequence[int], cls: Sequence[str], i: int, b: str, a: str) -> str | None:
    """LB11–LB18 (WJ/GL glue, closing-punct/OP, unresolved quotes, the decimal-mark exception, spaces).
    ``None`` falls through to LB19+."""
    # LB11 WJ; LB12/LB12a GL; LB13 no break before CL/CP/EX/SY; LB14 no break after OP (across SP).
    if a == "WJ" or b in {"WJ", "GL"}:
        return PROHIBITED
    if a == "GL" and b not in {"SP", "BA", "HY"}:
        return PROHIBITED
    if a in {"CL", "CP", "EX", "SY"} or _prev_nonsp(cls, i) == "OP":
        return PROHIBITED
    r = _lb15(cps, cls, i, b, a)
    if r is not None:
        return r
    # LB16 (CL|CP) SP* × NS; LB17 B2 SP* × B2; LB18 break after SP.
    prev = _prev_nonsp(cls, i)
    if (prev in {"CL", "CP"} and a == "NS") or (prev == "B2" and a == "B2"):
        return PROHIBITED
    return ALLOWED if b == "SP" else None


def _lb15(cps: Sequence[int], cls: Sequence[str], i: int, b: str, a: str) -> str | None:
    """LB15a/b (unresolved initial/final quotes) and LB15c/d (the ``SP ÷ IS NU`` decimal-mark
    exception, then ``× IS``). ``None`` falls through."""
    if _is_lb15a(cps, cls, i) or _is_lb15b(cps, cls, i):
        return PROHIBITED
    if b == "SP" and a == "IS" and i + 1 < len(cls) and cls[i + 1] == "NU":
        return ALLOWED  # LB15c: SP ÷ IS NU
    return PROHIBITED if a == "IS" else None  # LB15d


def _lb19(cps: Sequence[int], cls: Sequence[str], i: int, b: str, a: str) -> bool:
    """LB19 (non-initial/-final quotes) + LB19a (quotes not surrounded by East Asian chars)."""
    if a == "QU" and _pi(cps[i]) != "Pi":
        return True
    if b == "QU" and _pi(cps[i - 1]) != "Pf":
        return True
    return _lb19a(cps, cls, i, b, a)


def _lb20a(cls: Sequence[str], i: int, b: str, a: str) -> bool:
    """LB20a: no break after a word-initial hyphen (a hyphen at sot / after a break/space/CB/GL)."""
    return (
        b in {"HY", "HH"}
        and a == "AL"
        and (i < 2 or cls[i - 2] in {"BK", "CR", "LF", "NL", "SP", "ZW", "CB", "GL"})
    )


def _lb21a(cps: Sequence[int], cls: Sequence[str], i: int, b: str, a: str) -> bool:
    """LB21a: no break after the hyphen in ``Hebrew HY/BA non-Hebrew``."""
    return (
        i >= 2 and cls[i - 2] == "HL" and b in {"HY", "BA"} and not _is_ea(cps[i - 1]) and a != "HL"
    )


def _lb19_onward(cps: Sequence[int], cls: Sequence[str], i: int, b: str, a: str) -> str | None:
    """LB19–LB30b (continuation of :func:`_boundary`); ``None`` falls through to LB31."""
    if _lb19(cps, cls, i, b, a):
        return PROHIBITED
    if a == "CB" or b == "CB":  # LB20 break around CB
        return ALLOWED
    if _lb20a(cls, i, b, a):
        return PROHIBITED
    # LB21 × BA/HY/HH/NS, BB ×; LB21a Hebrew hyphen; LB21b SY × HL; LB22 × IN.
    if a in {"BA", "HY", "HH", "NS"} or b == "BB" or _lb21a(cps, cls, i, b, a):
        return PROHIBITED
    if (b == "SY" and a == "HL") or a == "IN":
        return PROHIBITED
    return _lb23_onward(cps, cls, i, b, a)


# Pure pairwise no-break rules (LB23/LB23a/LB24 numbers+letters, LB26/LB27 Korean, LB28/LB29): a break
# is prohibited when the left class is in ``B`` and the right in ``A``. The context-sensitive rules
# (LB25 numeric runs, LB28a Brahmic, LB30/30a/30b) stay explicit in _lb23_onward.
_JAMO = ("JL", "JV", "JT", "H2", "H3")
_PAIR_NOBREAK: tuple[tuple[tuple[str, ...], tuple[str, ...]], ...] = (
    (("AL", "HL"), ("NU",)),  # LB23
    (("NU",), ("AL", "HL")),
    (("PR",), ("ID", "EB", "EM")),  # LB23a
    (("ID", "EB", "EM"), ("PO",)),
    (("PR", "PO"), ("AL", "HL")),  # LB24
    (("AL", "HL"), ("PR", "PO")),
    (("JL",), ("JL", "JV", "H2", "H3")),  # LB26
    (("JV", "H2"), ("JV", "JT")),
    (("JT", "H3"), ("JT",)),
    (_JAMO, ("PO",)),  # LB27
    (("PR",), _JAMO),
    (("AL", "HL"), ("AL", "HL")),  # LB28
    (("IS",), ("AL", "HL")),  # LB29
)


def _lb23_onward(cps: Sequence[int], cls: Sequence[str], i: int, b: str, a: str) -> str | None:
    """LB23–LB30b. The pure pairwise rules are the ``_PAIR_NOBREAK`` table; the rest need context."""
    if any(b in left and a in right for left, right in _PAIR_NOBREAK):
        return PROHIBITED
    if _lb25(cls, i, b, a) or _lb28a(cls, i, b, a):  # LB25 numeric runs, LB28a Brahmic syllables
        return PROHIBITED
    # LB30 AL/HL/NU × OP (non-EA); CP (non-EA) × AL/HL/NU.
    if b in {"AL", "HL", "NU"} and a == "OP" and not _is_ea(cps[i]):
        return PROHIBITED
    if b == "CP" and not _is_ea(cps[i - 1]) and a in {"AL", "HL", "NU"}:
        return PROHIBITED
    # LB30a RI pairs (glue only an odd-indexed pair); LB30b emoji modifier bases.
    if b == "RI" and a == "RI" and _ri_odd_run(cls, i):
        return PROHIBITED
    if b == "EB" and a == "EM":
        return PROHIBITED
    if a == "EM" and _is_ext_pict(cps[i - 1]) and unicodedata.category(chr(cps[i - 1])) == "Cn":
        return PROHIBITED  # LB30b: [ExtPict & Cn] × EM
    return None


def _prev_nonsp(cls: Sequence[str], i: int) -> str:
    """Class of the nearest non-SP base before ``i`` (for the ``X SP* ×`` rules)."""
    j = i - 1
    while j > 0 and cls[j] == "SP":
        j -= 1
    return cls[j]


def _is_lb15a(cps: Sequence[int], cls: Sequence[str], i: int) -> bool:
    """LB15a: an initial (Pi) quote at sot / after BK/CR/LF/NL/OP/QU/GL/SP/ZW binds forward (SP* ×)."""
    j = i - 1
    while j > 0 and cls[j] == "SP":
        j -= 1
    if not (cls[j] == "QU" and _pi(cps[j]) == "Pi"):
        return False
    return j == 0 or cls[j - 1] in {"BK", "CR", "LF", "NL", "OP", "QU", "GL", "SP", "ZW"}


_LB15B_AFTER = ("SP", "GL", "WJ", "CL", "QU", "CP", "EX", "IS", "SY", "BK", "CR", "LF", "NL", "ZW")


def _is_lb15b(cps: Sequence[int], cls: Sequence[str], i: int) -> bool:
    """LB15b: no break before a final (Pf) quote that is itself followed by SP/GL/…/eot."""
    if not (cls[i] == "QU" and _pi(cps[i]) == "Pf"):
        return False
    return i + 1 >= len(cls) or cls[i + 1] in _LB15B_AFTER


def _lb19a(cps: Sequence[int], cls: Sequence[str], i: int, b: str, a: str) -> bool:
    """LB19a: don't break either side of a quote unless it is surrounded by East Asian characters."""
    if a == "QU" and (not _is_ea(cps[i - 1]) or i + 1 >= len(cls) or not _is_ea(cps[i + 1])):
        return True
    return b == "QU" and (not _is_ea(cps[i]) or i < 2 or not _is_ea(cps[i - 2]))


def _lb25(cls: Sequence[str], i: int, b: str, a: str) -> bool:
    """LB25 (17.0 pairwise expansion): keep a numeric expression together — ``PR/PO`` and ``OP/HY/IS``
    around ``NU``, a ``NU (SY|IS)*`` run, and a ``NU (SY|IS)* (CL|CP)?`` run before ``PO/PR``."""
    if a == "NU" and b in {"HY", "IS", "PR", "PO"}:
        return True
    if a == "NU" and b in {"NU", "SY", "IS"} and _num_run_before(cls, i):
        return True
    if b in {"PR", "PO"} and a == "OP":
        nxt = cls[i + 1] if i + 1 < len(cls) else ""
        return nxt == "NU" or (nxt == "IS" and i + 2 < len(cls) and cls[i + 2] == "NU")
    return a in {"PO", "PR"} and _num_run_before(cls, i)


def _num_run_before(cls: Sequence[str], i: int) -> bool:
    """True when position ``i-1`` ends a ``NU (SY|IS)* (CL|CP)?`` numeric run (for LB25)."""
    j = i - 1
    if cls[j] in {"CL", "CP"}:
        j -= 1
    while j >= 0 and cls[j] in {"SY", "IS"}:
        j -= 1
    return j >= 0 and cls[j] == "NU"


def _lb28a(cls: Sequence[str], i: int, b: str, a: str) -> bool:
    """LB28a: do not break inside a Brahmic orthographic syllable. ◌ (U+25CC, class AL) is not modelled
    here — it never occurs in the scripts this renderer wraps — so only the concrete AK/AS bases glue."""
    dotted = ("AK", "AS")
    if b == "AP" and a in dotted:
        return True
    if b in dotted and a in {"VF", "VI"}:
        return True
    if b == "VI" and a in {"AK", "AL"} and i >= 2 and cls[i - 2] in dotted:
        return True
    return b in dotted and a in dotted and i + 1 < len(cls) and cls[i + 1] == "VF"


@cache
def _pi(cp: int) -> str:
    """The ``Pi``/``Pf`` (initial/final quote) General_Category, else ``""`` — for the quote rules."""
    c = unicodedata.category(chr(cp))
    return c if c in {"Pi", "Pf"} else ""


@cache
def _is_ea(cp: int) -> bool:
    """East_Asian_Width F/W/H — the LB19a/LB21a/LB30 East-Asian exclusion."""
    return unicodedata.east_asian_width(chr(cp)) in {"F", "W", "H"}


def _ri_odd_run(cls: Sequence[str], i: int) -> bool:
    """LB30a: glue an RI–RI boundary only when an odd number of RI precede it (so pairs stay whole)."""
    j = i - 1
    n = 0
    while j >= 0 and cls[j] == "RI":
        n += 1
        j -= 1
    return n % 2 == 1


@lru_cache(maxsize=4096)
def _pair_breakable(left_char: str, right_char: str) -> bool:
    """May a line break fall between two adjacent chars? Memoised over the (small) set of boundary
    char-pairs a script produces, so wrapping a heavy entry pays the char algorithm once per pair."""
    return break_opportunities(left_char + right_char)[1] != PROHIBITED


def _unit_break_allowed(texts: Sequence[str]) -> list[bool]:
    """``allow[k]``: may a line break fall *before* unit ``k``? Decided by the character algorithm on the
    left unit's last char + the right unit's first char (the boundary classes), so unit wrapping and the
    character corpus share one implementation. A zero-text unit (image/chip) is breakable on either side."""
    n = len(texts)
    allow = [False] * n
    for k in range(1, n):
        left, right = texts[k - 1], texts[k]
        allow[k] = _pair_breakable(left[-1], right[0]) if left and right else True
    return allow


def _is_space(text: str) -> bool:
    return bool(text) and not text.strip()


class _Filler:
    """Mutable greedy-wrap accumulator (function-scoped, one per :func:`wrap_units` call — no shared
    state). ``add`` places a unit, breaking at the last opportunity (``last_bp``) on overflow so the tail
    rides to the next line; ``newline`` is a hard break."""

    def __init__(self, widths: Sequence[float], max_width: float, allow: Sequence[bool]):
        self._widths = widths
        self._max = max_width
        self._allow = allow
        self.lines: list[list[int]] = []
        self._line: list[int] = []
        self._x = 0.0
        self._last_bp = -1  # index in the current line of the most recent break opportunity

    @property
    def line_empty(self) -> bool:
        return not self._line

    def newline(self) -> None:
        self.lines.append(self._line)
        self._line, self._x, self._last_bp = [], 0.0, -1

    def add(self, k: int) -> None:
        if not self._line:
            self._line, self._x, self._last_bp = [k], self._widths[k], -1
            return
        overflow = self._x + self._widths[k] > self._max
        split = (len(self._line) if self._allow[k] else self._last_bp) if overflow else 0
        if split > 0:
            self.lines.append(self._line[:split])
            self._line = [*self._line[split:], k]
            self._x = sum(self._widths[c] for c in self._line)
            self._last_bp = -1
            return
        if self._allow[k]:
            self._last_bp = len(self._line)
        self._line.append(k)
        self._x += self._widths[k]

    def finish(self) -> list[list[int]]:
        if self._line:
            self.lines.append(self._line)
        return self.lines


def wrap_units(
    widths: Sequence[float],
    texts: Sequence[str],
    max_width: float,
    *,
    force_break: Callable[[int], bool] | None = None,
) -> list[list[int]]:
    """Greedy last-opportunity width-fill of atomic units into lines ≤ ``max_width``, breaking only where
    UAX #14 allows — so kinsoku falls out for free (a line never starts on a NO_START char nor ends on a
    NO_END one, because the algorithm forbids that boundary).

    ``widths[k]``/``texts[k]`` describe unit ``k``; ``texts[k]`` is its text (a single CJK char, a Latin
    word, a space run, or a ruby group's base) — a break lands *between* units, never inside one (ruby
    stays whole). ``force_break(k)`` marks a hard break (newline) before unit ``k``; that marker is
    consumed, not placed. A leading space on a fresh line is dropped. Returns lines of unit indices."""
    if not widths:
        return []
    fill = _Filler(widths, max_width, _unit_break_allowed(texts))
    for k in range(len(widths)):
        if force_break is not None and force_break(k):
            fill.newline()
        elif not (fill.line_empty and _is_space(texts[k])):  # drop a leading space on a fresh line
            fill.add(k)
    return fill.finish()
