"""Shared conformance-corpus oracle — a port of Yomitan's fixture ``hasTermReasons``.

Both the Japanese *stolen-suite* corpus (``test_yomitan_transform_corpus.py``, transcribed from
``japanese-transforms.test.js``) and the French *differential* corpus (``test_transform_differential_corpus.py``,
generated by running Yomitan's ``LanguageTransformer``) assert the same relation against the same
accessor, differing only in language + how the vectors were sourced — so the assertion lives here once.
"""

from __future__ import annotations

from saitenka_deinflect import condition_flags, conditions_match, deinflect


def has_term_reasons(
    source: str, term: str, rule: str | None, reasons: list[str], *, language: str = "ja"
) -> bool:
    """Does any deinflection of ``source`` reach ``term`` with matching POS conditions (skipped when
    ``rule is None``) and the exact transform chain ``reasons``? Port of Yomitan's ``hasTermReasons``."""
    rule_flags = None if rule is None else condition_flags(rule, language=language)
    for d in deinflect(source, language=language):
        if d.text != term:
            continue
        if rule_flags is not None and not conditions_match(d.conditions, rule_flags):
            continue
        if list(d.chain) == reasons:
            return True
    return False
